import { type NextPage } from "next";
import Head from "next/head";
import BackgroundDecoration from "~/components/BackgroundDecoration";
import Tetris from "../components/Tetris/Tetris";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <BackgroundDecoration />
      <main className="flex flex-col items-center justify-center min-h-screen bg-gradient-to-r from-[#3A506B] to-black">
        <Tetris />
      </main>
    </>
  );
};

export default Home;
