import { type NextPage } from "next";
import Head from "next/head";
import Board from "~/components/Board";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex flex-col items-center justify-center min-h-screen border-2 border-red-500">
        <Board />
      </main>
    </>
  );
};

export default Home;
